name: Main

on:
  pull_request:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure environment
      id: context
      run: echo ::set-output name=tag::$(yq '.metadata.version' manifest.yaml)

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      run: |
        docker login \
          -u ${{ github.actor }} \
          -p ${{ secrets.GITHUB_TOKEN }} \
          ${{ env.REGISTRY }}

    - name: Set image metadata
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=raw,value=${{ steps.context.outputs.tag }}
        flavor: |
          latest=true
    
    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          TAILSCALE_VERSION=${{ steps.context.outputs.tag }}
